version: '3.8'

services:
  backend:
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app/app
    environment:
      - PYTHONPATH=/app
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    env_file:
      - .env

  test:
    build:
      context: .
    environment:
      - PYTHONPATH=/app
      - OPENAI_API_KEY=test
    command: ["pytest"]
