version: '3.8'

services:
  backend:
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app/app
      - ./cookies.json:/app/cookies.json
    environment:
      - PYTHONPATH=/app
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - TWITTER_USERNAME=${TWITTER_USERNAME}
      - TWITTER_COOKIES_FILE=${TWITTER_COOKIES_FILE}
    env_file:
      - .env

  test:
    build:
      context: .
    environment:
      - PYTHONPATH=/app
      - OPENAI_API_KEY=test
      - TWITTER_USERNAME=testuser
    command: ["pytest"]
